name: Bazel Test Runner

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Bazelisk
      uses: bazelbuild/setup-bazelisk@v1
      with:
        version: '6.1.1'

    - name: Run Bazel Tests
      run: bazel test //...